[package]
name = "aw-watcher-media-player"
version = "0.0.1"
edition = "2021"
description = "A cross-platform watcher to send currently playing data to ActivityWatch."

[dependencies]
aw-client-rust = { git = "https://github.com/ActivityWatch/aw-server-rust", rev = "448312d" }
anyhow = "1.0.75"
chrono = "0.4.31"
gethostname = "0.4.3"
serde_json = "1.0.107"
signal-hook = "0.3.17"
log = { version = "0.4.20", features = ["std"] }
simple_logger = "4.2.0"

[target.'cfg(unix)'.dependencies]
mpris = "2.0.1"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.51.1"
features = [
	"Foundation",
	"Media_Control",
]
