[package]
name = "aw-watcher-media-player"
version = "0.0.1"
edition = "2021"

[dependencies]
aw-client-rust = { git = "https://github.com/ActivityWatch/aw-server-rust", rev = "448312d" }
anyhow = "1.0.75"
chrono = "0.4.31"
gethostname = "0.4.3"
serde_json = "1.0.107"
mpris = "2.0.1"
signal-hook = "0.3.17"
