name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v[0-9]*.*.*'
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    # 22.04 is the earliest version with OpenSSL 3
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo apt-get install build-essential -y
          sudo apt-get install libdbus-1-dev -y
          sudo apt-get install libssl-dev -y
          sudo apt-get install pkg-config -y

      # Buil and upload binary
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: zip "aw-watcher-media-player.zip" aw-watcher-media-player
        working-directory: target/release
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/aw-watcher-media-player.zip
